name: ci-build
on: [push]

jobs:
  windows-test:
    name: build-test-windows
    strategy:
      matrix:
        os: [windows-latest]
        java: [8,11,14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Assemble with Gradle
        run: gradlew.bat -i assemble
      - name: Test script with Gradle
        run: gradlew.bat -i -S check